name: Feature request
description: Template for new tasks. Please fill in all required fields (marked with an asterisk *).

body:
  - type: textarea
    attributes:
      label: What is this about?*
      description: A clear and concise description of the task
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instructions
      description: Provide steps to finish the task
  - type: textarea
    attributes:
      label: Additional considerations
      description: Provide observations about this case.
      value: ''
  - type: textarea
    attributes:
      label: Images (not required)
      description: Relevant images about the issue
      placeholder: Paste or upload your image with a title.
labels:
- enhancement
